export interface RecipeType {
  id: number;
  name: string;
  image: string;
  cookTime: number; // Changed from string to number
  servings: number;
  description: string;
  ingredients: string[];
  instructions: string[];
  cuisineType: string;
  favorites: number;
  // isPublic: boolean;
}

const RECIPES: RecipeType[] = [
  {
    id: 1,
    name: 'Creamy Garlic Pasta',
    image: 'https://images.unsplash.com/photo-1693820206774-d4a769355142?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 20,
    servings: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    ingredients: ['200g pasta', '4 cloves garlic (minced)', '1 cup heavy cream', '1/2 cup parmesan cheese', '2 tbsp butter', 'Salt and pepper'],
    instructions: ['Cook pasta according to package instructions.', 'Melt butter and sauté garlic until fragrant.', 'Add cream and simmer for 5 minutes.', 'Stir in parmesan cheese.', 'Combine with pasta and season to taste.'],
    cuisineType: 'Italian',
    favorites: 31251,
  },
  {
    id: 2,
    name: 'Spicy Tomato Penne',
    image: 'https://images.unsplash.com/photo-1693820206848-6ad84857832a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 25,
    servings: 3,
    description: 'Bold and zesty penne pasta tossed in a spicy tomato sauce with crushed red pepper and fresh basil.',
    ingredients: ['250g penne pasta', '2 cups tomato sauce', '1 tsp chili flakes', '2 cloves garlic', 'Fresh basil', 'Olive oil'],
    instructions: ['Cook penne pasta until al dente.', 'Heat oil and sauté garlic.', 'Add tomato sauce and chili flakes.', 'Simmer for 10 minutes.', 'Mix pasta with sauce and garnish with basil.'],
    cuisineType: 'Italian',
    favorites: 6,
  },
  {
    id: 3,
    name: 'Chocolate Layer Cake',
    image: 'https://images.unsplash.com/photo-1585601356536-270d51fe07a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 90,
    servings: 12,
    description: 'Decadent chocolate cake with layers of rich frosting and chocolate shavings. A showstopper for any celebration.',
    ingredients: ['2 cups flour', '1 3/4 cups sugar', '3/4 cup cocoa powder', '2 eggs', '1 cup milk', '1/2 cup butter'],
    instructions: ['Preheat oven to 180°C.', 'Mix dry ingredients together.', 'Add wet ingredients and combine.', 'Pour into pans and bake for 30-35 minutes.', 'Cool and frost between layers.'],
    cuisineType: 'American',
    favorites: 2,
  },
  {
    id: 4,
    name: 'Crispy Nachos Supreme',
    image: 'https://images.unsplash.com/photo-1776178393300-48bc87f3b65b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 15,
    servings: 6,
    description: 'Loaded nachos with melted cheese, jalapeños, corn, and your favorite toppings. Perfect for game day!',
    ingredients: ['Tortilla chips', '1 cup shredded cheese', 'Jalapeños', 'Corn kernels', 'Sour cream', 'Salsa'],
    instructions: ['Preheat oven to 180°C.', 'Spread chips on a tray.', 'Top with cheese, jalapeños, and corn.', 'Bake until cheese melts.', 'Serve with sour cream and salsa.'],
    cuisineType: 'Mexican',
    favorites: 23,
  },
  {
    id: 5,
    name: 'Mini Berry Tarts',
    image: 'https://images.unsplash.com/photo-1764813823855-3ef4ad5f863d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 45,
    servings: 8,
    description: 'Delicate tart shells filled with vanilla cream and topped with fresh berries and a berry glaze.',
    ingredients: ['Tart shells', '1 cup whipped cream', 'Vanilla extract', 'Mixed berries', 'Sugar glaze'],
    instructions: ['Prepare tart shells and let cool.', 'Whip cream with vanilla.', 'Fill shells with cream.', 'Top with fresh berries.', 'Brush with glaze before serving.'],
    cuisineType: 'French',
    favorites: 8,
  },
  {
    id: 6,
    name: 'Grilled Chicken Bowl',
    image: 'https://images.unsplash.com/photo-1748012199673-d990c72aaa57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 2,
    description: 'Healthy grilled chicken served with roasted vegetables, quinoa, and a tangy lemon herb dressing.',
    ingredients: ['2 chicken breasts', '1 cup quinoa', 'Mixed vegetables', 'Lemon juice', 'Olive oil', 'Salt and pepper'],
    instructions: ['Season and grill chicken until cooked.', 'Cook quinoa according to instructions.', 'Roast vegetables with olive oil.', 'Slice chicken and assemble bowl.', 'Drizzle with lemon dressing.'],
    cuisineType: 'American',
    favorites: 0,
  },
  {
    id: 7,
    name: 'Pesto Pasta Primavera',
    image: 'https://images.unsplash.com/photo-1748012199657-3f34292cdf70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 25,
    servings: 4,
    description: 'Fresh pasta tossed with homemade pesto, seasonal vegetables, and parmesan cheese.',
    ingredients: ['200g pasta', '1/2 cup pesto', 'Zucchini', 'Cherry tomatoes', 'Parmesan cheese'],
    instructions: ['Cook pasta until al dente.', 'Sauté vegetables lightly.', 'Mix pasta with pesto.', 'Add vegetables and toss.', 'Top with parmesan cheese.'],
    cuisineType: 'Italian',
    favorites: 67,
  },
  {
    id: 8,
    name: 'Creamy Tuscan Chicken',
    image: 'https://images.unsplash.com/photo-1748012199672-2a94ab9cbb19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 35,
    servings: 4,
    description: 'Tender chicken in a creamy sun-dried tomato sauce with spinach and garlic. Served with crusty bread.',
    ingredients: ['2 chicken breasts', '1 cup heavy cream', 'Sun-dried tomatoes', 'Spinach', 'Garlic', 'Parmesan cheese'],
    instructions: ['Cook chicken until golden and set aside.', 'Sauté garlic and sun-dried tomatoes.', 'Add cream and simmer.', 'Stir in spinach and parmesan.', 'Return chicken and cook until done.'],
    cuisineType: 'Italian',
    favorites: 3,
  },
  {
    id: 9,
    name: 'Chicken Adobo',
    image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 45,
    servings: 4,
    description: 'Classic Filipino braised chicken in vinegar, soy sauce, garlic, and bay leaves. Savory, tangy, and deeply comforting.',
    ingredients: ['1kg chicken pieces', '1/2 cup soy sauce', '1/2 cup white vinegar', '1 head garlic', '3 bay leaves', '1 tsp black pepper'],
    instructions: ['Combine chicken with soy sauce, vinegar, garlic, and bay leaves.', 'Marinate for 30 minutes.', 'Bring to a boil then simmer for 30 minutes.', 'Reduce sauce until thick.', 'Serve over steamed rice.'],
    cuisineType: 'Filipino',
    favorites: 5420,
  },
  {
    id: 10,
    name: 'Sinigang na Baboy',
    image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 60,
    servings: 6,
    description: 'Hearty Filipino sour soup with pork ribs, vegetables, and tamarind broth. A true taste of home.',
    ingredients: ['1kg pork ribs', '1 pack tamarind mix', 'Radish', 'String beans', 'Eggplant', 'Spinach', 'Tomatoes', 'Onion'],
    instructions: ['Boil pork ribs until tender.', 'Add tamarind mix and bring to a boil.', 'Add radish and string beans.', 'Add eggplant and simmer.', 'Add spinach and season to taste.'],
    cuisineType: 'Filipino',
    favorites: 4890,
  },
  {
    id: 11,
    name: 'Beef Kare-Kare',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 90,
    servings: 6,
    description: 'Rich Filipino peanut stew with oxtail, banana blossom, and vegetables. Served with bagoong.',
    ingredients: ['1kg oxtail', '1 cup peanut butter', 'Banana blossom', 'Eggplant', 'String beans', 'Annatto seeds', 'Bagoong'],
    instructions: ['Boil oxtail until tender.', 'Sauté annatto seeds for color.', 'Add peanut butter and broth.', 'Add vegetables and simmer.', 'Serve with bagoong on the side.'],
    cuisineType: 'Filipino',
    favorites: 3210,
  },
  {
    id: 12,
    name: 'Sushi Rolls',
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 40,
    servings: 4,
    description: 'Classic Japanese maki rolls with fresh salmon, cucumber, and seasoned sushi rice wrapped in nori.',
    ingredients: ['2 cups sushi rice', 'Nori sheets', '200g fresh salmon', '1 cucumber', 'Rice vinegar', 'Soy sauce', 'Wasabi'],
    instructions: ['Cook and season sushi rice.', 'Place nori on bamboo mat.', 'Spread rice evenly on nori.', 'Add salmon and cucumber.', 'Roll tightly and slice.'],
    cuisineType: 'Japanese',
    favorites: 8930,
  },
  {
    id: 13,
    name: 'Ramen',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 120,
    servings: 2,
    description: 'Rich tonkotsu ramen with creamy pork bone broth, chashu pork, soft-boiled eggs, and fresh noodles.',
    ingredients: ['Ramen noodles', 'Pork bones', 'Chashu pork', '2 soft-boiled eggs', 'Nori', 'Green onions', 'Bamboo shoots'],
    instructions: ['Simmer pork bones for 4 hours for broth.', 'Cook ramen noodles separately.', 'Prepare chashu pork and slice.', 'Assemble bowl with noodles and broth.', 'Top with egg, pork, and garnishes.'],
    cuisineType: 'Japanese',
    favorites: 12400,
  },
  {
    id: 14,
    name: 'Bibimbap',
    image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 40,
    servings: 2,
    description: 'Korean mixed rice bowl with assorted vegetables, bulgogi beef, a fried egg, and gochujang sauce.',
    ingredients: ['2 cups steamed rice', 'Bulgogi beef', 'Spinach', 'Bean sprouts', 'Carrots', 'Zucchini', '2 eggs', 'Gochujang'],
    instructions: ['Cook and season each vegetable separately.', 'Prepare bulgogi beef.', 'Fry eggs sunny side up.', 'Arrange vegetables and beef over rice.', 'Top with egg and gochujang.'],
    cuisineType: 'Korean',
    favorites: 7650,
  },
  {
    id: 15,
    name: 'Korean Fried Chicken',
    image: 'https://images.unsplash.com/photo-1609016948902-cf8b5b438a78?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 50,
    servings: 4,
    description: 'Double-fried crispy Korean chicken glazed in sweet and spicy gochujang sauce. Addictively good.',
    ingredients: ['1kg chicken wings', '1 cup cornstarch', 'Gochujang', 'Honey', 'Garlic', 'Soy sauce', 'Sesame seeds'],
    instructions: ['Coat chicken in cornstarch and fry twice.', 'Make sauce with gochujang, honey, and garlic.', 'Toss fried chicken in sauce.', 'Sprinkle sesame seeds.', 'Serve immediately.'],
    cuisineType: 'Korean',
    favorites: 9870,
  },
  {
    id: 16,
    name: 'Pad Thai',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8892059e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 2,
    description: 'Classic Thai stir-fried rice noodles with shrimp, tofu, bean sprouts, and a tangy tamarind sauce.',
    ingredients: ['200g rice noodles', 'Shrimp', 'Tofu', 'Bean sprouts', 'Eggs', 'Tamarind paste', 'Fish sauce', 'Peanuts'],
    instructions: ['Soak noodles until soft.', 'Stir fry shrimp and tofu.', 'Add noodles and tamarind sauce.', 'Push aside and scramble eggs.', 'Mix together and top with peanuts.'],
    cuisineType: 'Thai',
    favorites: 6540,
  },
  {
    id: 17,
    name: 'Green Curry',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 35,
    servings: 4,
    description: 'Fragrant Thai green curry with chicken, coconut milk, Thai eggplant, and fresh basil leaves.',
    ingredients: ['2 chicken breasts', '2 cans coconut milk', '3 tbsp green curry paste', 'Thai eggplant', 'Kaffir lime leaves', 'Fish sauce', 'Thai basil'],
    instructions: ['Fry curry paste in oil until fragrant.', 'Add coconut milk and bring to simmer.', 'Add chicken and eggplant.', 'Season with fish sauce.', 'Finish with fresh basil leaves.'],
    cuisineType: 'Thai',
    favorites: 5230,
  },
  {
    id: 18,
    name: 'Butter Chicken',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 50,
    servings: 4,
    description: 'Tender chicken in a rich, creamy tomato-based sauce with aromatic Indian spices. Best with naan bread.',
    ingredients: ['1kg chicken', '2 cups tomato puree', '1 cup heavy cream', 'Butter', 'Garam masala', 'Cumin', 'Ginger', 'Garlic'],
    instructions: ['Marinate chicken in yogurt and spices.', 'Grill or bake chicken.', 'Make sauce with butter, tomatoes, and cream.', 'Add grilled chicken to sauce.', 'Simmer and serve with naan.'],
    cuisineType: 'Indian',
    favorites: 15600,
  },
  {
    id: 19,
    name: 'Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 75,
    servings: 6,
    description: 'Fragrant layered rice dish with spiced chicken, caramelized onions, saffron, and fresh herbs.',
    ingredients: ['3 cups basmati rice', '1kg chicken', 'Saffron', 'Caramelized onions', 'Yogurt', 'Whole spices', 'Fresh mint', 'Ghee'],
    instructions: ['Marinate chicken in spiced yogurt.', 'Par-cook basmati rice.', 'Layer rice and chicken in a pot.', 'Top with saffron milk and onions.', 'Dum cook on low heat for 25 minutes.'],
    cuisineType: 'Indian',
    favorites: 11200,
  },
  {
    id: 20,
    name: 'Tacos al Pastor',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 40,
    servings: 4,
    description: 'Classic Mexican street tacos with marinated pork, fresh pineapple, cilantro, and onion in corn tortillas.',
    ingredients: ['500g pork shoulder', 'Dried chilies', 'Pineapple', 'Corn tortillas', 'Cilantro', 'Onion', 'Lime'],
    instructions: ['Marinate pork in chili and spices overnight.', 'Grill or pan fry pork until charred.', 'Slice thinly.', 'Warm tortillas and assemble tacos.', 'Top with pineapple, cilantro, and onion.'],
    cuisineType: 'Mexican',
    favorites: 8920,
  },
  {
    id: 21,
    name: 'Guacamole',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 10,
    servings: 4,
    description: 'Fresh and chunky Mexican avocado dip with lime, cilantro, jalapeño, and tomato. Perfect with tortilla chips.',
    ingredients: ['3 ripe avocados', '1 lime', 'Cilantro', '1 jalapeño', '1 tomato', 'Red onion', 'Salt'],
    instructions: ['Mash avocados to desired consistency.', 'Add lime juice immediately.', 'Dice tomato, onion, and jalapeño.', 'Fold in vegetables and cilantro.', 'Season with salt and serve.'],
    cuisineType: 'Mexican',
    favorites: 4320,
  },
  {
    id: 22,
    name: 'Croissants',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 180,
    servings: 8,
    description: 'Flaky, buttery French croissants with hundreds of crispy layers. A weekend baking project worth every minute.',
    ingredients: ['3 cups flour', '250g butter', '1 cup milk', '7g yeast', '2 tbsp sugar', '1 tsp salt', '1 egg'],
    instructions: ['Make dough and refrigerate overnight.', 'Laminate with butter layers.', 'Fold and chill three times.', 'Shape into crescents.', 'Proof and bake at 200°C until golden.'],
    cuisineType: 'French',
    favorites: 6780,
  },
  {
    id: 23,
    name: 'French Onion Soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 75,
    servings: 4,
    description: 'Classic French soup with deeply caramelized onions, rich beef broth, crusty croutons, and melted Gruyère.',
    ingredients: ['6 large onions', 'Beef broth', 'White wine', 'Gruyère cheese', 'Baguette slices', 'Butter', 'Thyme'],
    instructions: ['Caramelize onions in butter for 45 minutes.', 'Deglaze with white wine.', 'Add beef broth and simmer.', 'Pour into oven-safe bowls.', 'Top with bread and cheese and broil.'],
    cuisineType: 'French',
    favorites: 3450,
  },
  {
    id: 24,
    name: 'Margherita Pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 2,
    description: 'Authentic Neapolitan pizza with San Marzano tomatoes, fresh mozzarella, and basil on a thin crispy crust.',
    ingredients: ['Pizza dough', 'San Marzano tomatoes', 'Fresh mozzarella', 'Fresh basil', 'Olive oil', 'Salt'],
    instructions: ['Stretch dough to thin circle.', 'Spread crushed tomatoes.', 'Tear mozzarella over top.', 'Bake at highest oven temp for 10 minutes.', 'Finish with fresh basil and olive oil.'],
    cuisineType: 'Italian',
    favorites: 21300,
  },
  {
    id: 25,
    name: 'Risotto ai Funghi',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 45,
    servings: 4,
    description: 'Velvety Italian mushroom risotto with porcini, arborio rice, white wine, and parmesan cheese.',
    ingredients: ['2 cups arborio rice', 'Porcini mushrooms', '1/2 cup white wine', 'Parmesan cheese', 'Butter', 'Shallots', 'Chicken stock'],
    instructions: ['Sauté shallots and mushrooms.', 'Add rice and toast lightly.', 'Deglaze with white wine.', 'Add stock ladle by ladle, stirring constantly.', 'Finish with butter and parmesan.'],
    cuisineType: 'Italian',
    favorites: 4560,
  },
  {
    id: 26,
    name: 'Paella',
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 60,
    servings: 6,
    description: 'Spanish saffron rice cooked with chicken, chorizo, shrimp, mussels, and colorful bell peppers.',
    ingredients: ['3 cups bomba rice', 'Saffron', 'Chicken thighs', 'Chorizo', 'Shrimp', 'Mussels', 'Bell peppers', 'Tomatoes'],
    instructions: ['Brown chicken and chorizo.', 'Sauté vegetables and add rice.', 'Add saffron broth.', 'Arrange seafood on top.', 'Cook until socarrat forms on bottom.'],
    cuisineType: 'Spanish',
    favorites: 7890,
  },
  {
    id: 27,
    name: 'Gazpacho',
    image: 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 15,
    servings: 4,
    description: 'Refreshing cold Spanish tomato soup blended with cucumber, peppers, garlic, and olive oil.',
    ingredients: ['6 ripe tomatoes', '1 cucumber', '1 bell pepper', '2 cloves garlic', 'Olive oil', 'Red wine vinegar', 'Bread'],
    instructions: ['Soak bread in water briefly.', 'Blend all vegetables together.', 'Add olive oil and vinegar.', 'Season with salt.', 'Chill for 2 hours before serving.'],
    cuisineType: 'Spanish',
    favorites: 2340,
  },
  {
    id: 28,
    name: 'Greek Salad',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 10,
    servings: 4,
    description: 'Classic Horiatiki salad with juicy tomatoes, cucumbers, olives, red onion, and a generous slab of feta.',
    ingredients: ['4 tomatoes', '1 cucumber', 'Kalamata olives', 'Red onion', '200g feta cheese', 'Olive oil', 'Oregano'],
    instructions: ['Chop tomatoes and cucumber into chunks.', 'Slice red onion thinly.', 'Combine with olives.', 'Place feta on top.', 'Drizzle with olive oil and sprinkle oregano.'],
    cuisineType: 'Greek',
    favorites: 3210,
  },
  {
    id: 29,
    name: 'Moussaka',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 90,
    servings: 6,
    description: 'Hearty Greek layered casserole with spiced ground beef, roasted eggplant, and creamy béchamel sauce.',
    ingredients: ['2 large eggplants', '500g ground beef', 'Tomato sauce', 'Cinnamon', 'Béchamel sauce', 'Parmesan cheese'],
    instructions: ['Roast eggplant slices until soft.', 'Cook spiced meat sauce.', 'Make béchamel sauce.', 'Layer eggplant, meat, and béchamel.', 'Bake at 180°C for 45 minutes.'],
    cuisineType: 'Greek',
    favorites: 4120,
  },
  {
    id: 30,
    name: 'Hummus',
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 10,
    servings: 6,
    description: 'Silky smooth Lebanese chickpea dip with tahini, lemon, and garlic. Served with warm pita bread.',
    ingredients: ['2 cans chickpeas', '1/3 cup tahini', '2 lemons', '2 cloves garlic', 'Olive oil', 'Cumin', 'Salt'],
    instructions: ['Blend chickpeas until smooth.', 'Add tahini, lemon juice, and garlic.', 'Blend with ice water for creaminess.', 'Season to taste.', 'Drizzle with olive oil and serve.'],
    cuisineType: 'Lebanese',
    favorites: 5670,
  },
  {
    id: 31,
    name: 'Falafel',
    image: 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 4,
    description: 'Crispy fried Middle Eastern chickpea fritters with herbs and spices. Served in pita with tahini sauce.',
    ingredients: ['2 cups dried chickpeas', 'Parsley', 'Cilantro', 'Garlic', 'Cumin', 'Coriander', 'Flour'],
    instructions: ['Soak chickpeas overnight.', 'Blend with herbs and spices.', 'Form into small balls.', 'Deep fry until golden brown.', 'Serve in pita with tahini.'],
    cuisineType: 'Lebanese',
    favorites: 4320,
  },
  {
    id: 32,
    name: 'Beef Bulgogi',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 25,
    servings: 4,
    description: 'Korean marinated beef grilled to perfection with soy sauce, sesame oil, garlic, and Asian pear.',
    ingredients: ['500g beef sirloin', 'Soy sauce', 'Sesame oil', 'Asian pear', 'Garlic', 'Sugar', 'Green onions'],
    instructions: ['Slice beef thinly.', 'Marinate in soy sauce, pear, and sesame oil.', 'Let marinate for 30 minutes.', 'Grill or pan fry over high heat.', 'Serve with rice and kimchi.'],
    cuisineType: 'Korean',
    favorites: 8760,
  },
  {
    id: 33,
    name: 'Tempura',
    image: 'https://images.unsplash.com/photo-1618841557871-b4664fbf0cb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 4,
    description: 'Light and crispy Japanese battered shrimp and vegetables served with a delicate dipping sauce.',
    ingredients: ['Shrimp', 'Assorted vegetables', '1 cup cold flour', '1 egg', 'Ice cold water', 'Dashi', 'Mirin', 'Soy sauce'],
    instructions: ['Make tempura batter with cold ingredients.', 'Heat oil to 180°C.', 'Dip shrimp and vegetables in batter.', 'Fry until light golden, about 2 minutes.', 'Drain and serve with dipping sauce.'],
    cuisineType: 'Japanese',
    favorites: 5430,
  },
  {
    id: 34,
    name: 'Pancit Canton',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 6,
    description: 'Filipino stir-fried egg noodles with chicken, shrimp, vegetables, and savory soy-based sauce.',
    ingredients: ['400g canton noodles', 'Chicken', 'Shrimp', 'Cabbage', 'Carrots', 'Soy sauce', 'Oyster sauce'],
    instructions: ['Sauté garlic and onion.', 'Add chicken and shrimp.', 'Add vegetables and noodles.', 'Season with soy and oyster sauce.', 'Toss and serve with calamansi.'],
    cuisineType: 'Filipino',
    favorites: 6540,
  },
  {
    id: 35,
    name: 'Lechon Kawali',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 90,
    servings: 6,
    description: 'Filipino crispy deep-fried pork belly with golden crackling skin. Served with liver sauce or vinegar.',
    ingredients: ['1kg pork belly', 'Salt', 'Garlic', 'Bay leaves', 'Black peppercorns', 'Oil for frying'],
    instructions: ['Boil pork belly with spices until tender.', 'Dry thoroughly and refrigerate.', 'Deep fry until golden and crispy.', 'Let rest and chop into pieces.', 'Serve with liver sauce.'],
    cuisineType: 'Filipino',
    favorites: 7890,
  },
  {
    id: 36,
    name: 'Massaman Curry',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 60,
    servings: 4,
    description: 'Rich and mildly spiced Thai curry with tender beef, potatoes, peanuts, and creamy coconut milk.',
    ingredients: ['500g beef', 'Massaman curry paste', '2 cans coconut milk', 'Potatoes', 'Peanuts', 'Cinnamon stick', 'Palm sugar'],
    instructions: ['Fry curry paste until fragrant.', 'Add beef and brown lightly.', 'Pour in coconut milk.', 'Add potatoes and peanuts.', 'Simmer until beef is tender.'],
    cuisineType: 'Thai',
    favorites: 4560,
  },
  {
    id: 37,
    name: 'Lamb Shawarma',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 50,
    servings: 4,
    description: 'Middle Eastern spiced lamb wrapped in flatbread with garlic sauce, pickles, and fresh vegetables.',
    ingredients: ['500g lamb', 'Shawarma spices', 'Flatbread', 'Garlic sauce', 'Pickled turnips', 'Tomatoes', 'Parsley'],
    instructions: ['Marinate lamb in shawarma spices.', 'Roast lamb until cooked through.', 'Slice thinly.', 'Warm flatbread.', 'Assemble with sauce and vegetables.'],
    cuisineType: 'Lebanese',
    favorites: 6780,
  },
  {
    id: 38,
    name: 'BBQ Ribs',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 180,
    servings: 4,
    description: 'Slow-cooked American BBQ pork ribs with smoky dry rub and sticky sweet barbecue glaze.',
    ingredients: ['2 racks pork ribs', 'BBQ rub spices', 'BBQ sauce', 'Apple cider vinegar', 'Brown sugar', 'Smoked paprika'],
    instructions: ['Apply dry rub to ribs.', 'Smoke or bake low and slow for 3 hours.', 'Wrap in foil and cook another hour.', 'Glaze with BBQ sauce.', 'Finish on grill for caramelization.'],
    cuisineType: 'American',
    favorites: 9870,
  },
  {
    id: 39,
    name: 'Clam Chowder',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 45,
    servings: 4,
    description: 'Creamy New England clam chowder with tender clams, potatoes, bacon, and a rich buttery broth.',
    ingredients: ['2 cans clams', 'Potatoes', 'Bacon', 'Onion', 'Heavy cream', 'Flour', 'Butter', 'Thyme'],
    instructions: ['Cook bacon until crispy.', 'Sauté onion in bacon fat.', 'Add flour to make roux.', 'Add clam juice, potatoes, and cream.', 'Add clams and season to taste.'],
    cuisineType: 'American',
    favorites: 3450,
  },
  {
    id: 40,
    name: 'Tiramisu',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 8,
    description: 'Classic Italian no-bake dessert with espresso-soaked ladyfingers, mascarpone cream, and cocoa powder.',
    ingredients: ['Ladyfinger biscuits', '500g mascarpone', '4 eggs', 'Espresso', 'Marsala wine', 'Cocoa powder', 'Sugar'],
    instructions: ['Whip egg yolks with sugar until pale.', 'Fold in mascarpone.', 'Whip egg whites and fold in.', 'Dip ladyfingers in espresso and layer.', 'Refrigerate overnight and dust with cocoa.'],
    cuisineType: 'Italian',
    favorites: 13400,
  },
  {
    id: 41,
    name: 'Beef Rendang',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 120,
    servings: 6,
    description: 'Indonesian dry beef curry slow-cooked in coconut milk and aromatic spices until deeply caramelized.',
    ingredients: ['1kg beef', 'Coconut milk', 'Lemongrass', 'Galangal', 'Turmeric', 'Chilies', 'Kaffir lime leaves'],
    instructions: ['Blend spice paste.', 'Combine beef with paste and coconut milk.', 'Cook on medium heat, stirring frequently.', 'Reduce until liquid evaporates.', 'Continue cooking until beef is dark and dry.'],
    cuisineType: 'Other',
    favorites: 7650,
  },
  {
    id: 42,
    name: 'Ceviche',
    image: 'https://images.unsplash.com/photo-1535400255456-984e0a070571?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 20,
    servings: 4,
    description: 'Fresh Peruvian seafood cured in lime juice with red onion, cilantro, and ají amarillo chili.',
    ingredients: ['500g fresh white fish', '1 cup lime juice', 'Red onion', 'Cilantro', 'Ají amarillo', 'Salt', 'Sweet potato'],
    instructions: ['Cut fish into small cubes.', 'Marinate in lime juice for 10 minutes.', 'Add sliced onion and chili.', 'Season and add cilantro.', 'Serve with sweet potato and corn.'],
    cuisineType: 'Other',
    favorites: 4320,
  },
  {
    id: 43,
    name: 'Shakshuka',
    image: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 25,
    servings: 2,
    description: 'Middle Eastern eggs poached in a spiced tomato and pepper sauce. Perfect for breakfast or brunch.',
    ingredients: ['4 eggs', '2 cups tomato sauce', 'Bell peppers', 'Cumin', 'Paprika', 'Garlic', 'Feta cheese'],
    instructions: ['Sauté peppers and garlic.', 'Add tomato sauce and spices.', 'Simmer for 10 minutes.', 'Create wells and crack in eggs.', 'Cover and cook until whites are set.'],
    cuisineType: 'Lebanese',
    favorites: 5670,
  },
  {
    id: 44,
    name: 'Dumplings',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 40,
    servings: 4,
    description: 'Handmade Chinese pork and cabbage dumplings pan-fried until crispy on the bottom. Served with black vinegar dip.',
    ingredients: ['Dumpling wrappers', '300g ground pork', 'Cabbage', 'Ginger', 'Soy sauce', 'Sesame oil', 'Green onions'],
    instructions: ['Mix pork with seasonings and cabbage.', 'Place filling in wrappers and seal.', 'Pan fry with oil until bottom is golden.', 'Add water and cover to steam.', 'Serve with vinegar dipping sauce.'],
    cuisineType: 'Chinese',
    favorites: 9870,
  },
  {
    id: 45,
    name: 'Mapo Tofu',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 25,
    servings: 4,
    description: 'Sichuan silken tofu in a fiery sauce of doubanjiang, ground pork, and numbing Sichuan peppercorns.',
    ingredients: ['400g silken tofu', 'Ground pork', 'Doubanjiang', 'Sichuan peppercorns', 'Garlic', 'Ginger', 'Chicken stock'],
    instructions: ['Fry pork until cooked.', 'Add doubanjiang and fry until fragrant.', 'Add garlic and ginger.', 'Pour in stock and add tofu gently.', 'Finish with Sichuan peppercorn oil.'],
    cuisineType: 'Chinese',
    favorites: 6540,
  },
  {
    id: 46,
    name: 'Beef Steak',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 20,
    servings: 2,
    description: 'Perfectly seared ribeye steak with garlic butter, thyme, and rosemary. Cooked to a perfect medium-rare.',
    ingredients: ['2 ribeye steaks', 'Butter', 'Garlic', 'Thyme', 'Rosemary', 'Salt', 'Black pepper'],
    instructions: ['Season steak generously with salt and pepper.', 'Sear in hot pan 3 minutes each side.', 'Add butter, garlic, and herbs.', 'Baste steak with butter repeatedly.', 'Rest for 5 minutes before serving.'],
    cuisineType: 'American',
    favorites: 18700,
  },
  {
    id: 47,
    name: 'Mango Sticky Rice',
    image: 'https://images.unsplash.com/photo-1621236378699-8597faf6a176?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 30,
    servings: 4,
    description: 'Classic Thai dessert with sweet glutinous rice, fresh ripe mango, and warm coconut cream sauce.',
    ingredients: ['2 cups glutinous rice', '2 ripe mangoes', '1 can coconut milk', 'Sugar', 'Salt', 'Sesame seeds'],
    instructions: ['Soak and steam glutinous rice.', 'Heat coconut milk with sugar and salt.', 'Mix half the coconut sauce with rice.', 'Slice mango.', 'Serve rice with mango and remaining sauce.'],
    cuisineType: 'Thai',
    favorites: 8920,
  },
  {
    id: 48,
    name: 'Crème Brûlée',
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 60,
    servings: 4,
    description: 'Classic French vanilla custard with a perfectly caramelized sugar crust. Elegant and irresistible.',
    ingredients: ['2 cups heavy cream', '5 egg yolks', '1/2 cup sugar', 'Vanilla bean', 'Extra sugar for topping'],
    instructions: ['Heat cream with vanilla.', 'Whisk egg yolks with sugar.', 'Temper cream into yolks slowly.', 'Bake in water bath at 160°C for 40 minutes.', 'Chill and torch sugar topping before serving.'],
    cuisineType: 'French',
    favorites: 9870,
  },
  {
    id: 49,
    name: 'Nasi Goreng',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 20,
    servings: 2,
    description: 'Indonesian fried rice with kecap manis, shrimp paste, chicken, and topped with a fried egg and crackers.',
    ingredients: ['2 cups cooked rice', 'Chicken', 'Shrimp', 'Kecap manis', 'Shrimp paste', 'Garlic', 'Eggs', 'Crackers'],
    instructions: ['Fry garlic and shrimp paste.', 'Add chicken and shrimp.', 'Add cold rice and stir fry.', 'Season with kecap manis.', 'Serve with fried egg and crackers.'],
    cuisineType: 'Other',
    favorites: 7650,
  },
  {
    id: 50,
    name: 'Baklava',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    cookTime: 75,
    servings: 24,
    description: 'Rich Middle Eastern pastry with layers of flaky phyllo, chopped pistachios, and sweet honey syrup.',
    ingredients: ['Phyllo dough', '2 cups pistachios', '1 cup butter', 'Honey', 'Sugar', 'Cinnamon', 'Rose water'],
    instructions: ['Layer phyllo sheets with butter.', 'Add pistachio layer in middle.', 'Continue layering phyllo.', 'Score into diamonds and bake at 160°C.', 'Pour honey syrup over hot baklava.'],
    cuisineType: 'Lebanese',
    favorites: 11200,
  },
];

export default RECIPES;
